#server:
#  port: 8082
logging:
  level:
    ROOT: INFO
#spring:
#  profiles:
#    active: prod
#  application:
#    admin:
#      enabled: TRUE
#management:
#  endpoints:
#    web:
#      exposure:
#        include: info, health, beans

message: "Test Props msg"