
package ru.otus.soap.wsclient.corptax;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CorporateTaxProvider", targetNamespace = "http://corptax.wservice.soap.otus.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CorporateTaxProvider {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentTax", targetNamespace = "http://corptax.wservice.soap.otus.ru/", className = "ru.otus.soap.wsclient.corptax.GetCurrentTax")
    @ResponseWrapper(localName = "getCurrentTaxResponse", targetNamespace = "http://corptax.wservice.soap.otus.ru/", className = "ru.otus.soap.wsclient.corptax.GetCurrentTaxResponse")
    @Action(input = "http://corptax.wservice.soap.otus.ru/CorporateTaxProvider/getCurrentTaxRequest", output = "http://corptax.wservice.soap.otus.ru/CorporateTaxProvider/getCurrentTaxResponse")
    public double getCurrentTax(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
